# Generated by Django 5.0.2 on 2024-05-12 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructorsCup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=255)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Cup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст новости')),
                ('date', models.DateField(verbose_name='Дата')),
                ('img', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('shortText', models.CharField(max_length=128, verbose_name='Кратко о новости')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Видео')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=256, verbose_name='Этап')),
                ('time', models.DateTimeField(verbose_name='Время')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=256, verbose_name='Имя')),
                ('email', models.CharField(max_length=256, verbose_name='Email')),
                ('password', models.CharField(max_length=256, verbose_name='Пароль')),
                ('image', models.ImageField(upload_to='', verbose_name='Аватар')),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_name', models.CharField(max_length=128, verbose_name='Название')),
                ('date', models.DateField(verbose_name='Дата')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='formula1site.user')),
            ],
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_text', models.TextField(verbose_name='Полный текст')),
                ('date', models.DateField(verbose_name='Дата')),
                ('image', models.ImageField(blank=True, null=True, upload_to='statement_images/', verbose_name='Изображение')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='formula1site.title')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='formula1site.user')),
            ],
        ),
    ]
