# Generated by Django 5.0.2 on 2024-05-13 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formula1site', '0005_vote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
