# Generated by Django 5.0.2 on 2024-05-13 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula1site', '0006_delete_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата комментария')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formula1site.user')),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Текст')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('date', models.DateField(verbose_name='Дата')),
                ('comments', models.ManyToManyField(blank=True, related_name='posts_commented', to='formula1site.comments')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formula1site.user')),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_to_post', to='formula1site.posts'),
        ),
    ]
