# Generated by Django 5.0.2 on 2024-05-15 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formula1site', '0007_comments_posts_comments_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='news',
            name='likes',
        ),
    ]
