# Generated by Django 5.0.2 on 2024-05-15 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formula1site', '0008_remove_news_dislikes_remove_news_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='shortText',
        ),
    ]
