# Generated by Django 5.0.2 on 2024-05-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula1site', '0012_remove_title_teg_remove_title_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(related_name='users', through='formula1site.GroupMembership', to='formula1site.group'),
        ),
    ]
