# Generated by Django 5.0.2 on 2024-05-17 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula1site', '0014_meme'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='formula1site.group'),
            preserve_default=False,
        ),
    ]
