# Generated by Django 5.0.2 on 2024-05-17 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula1site', '0015_meme_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Изображение'),
        ),
    ]
