# Generated by Django 5.0.2 on 2024-05-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula1site', '0018_tag_news_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='В сети'),
        ),
    ]
