# Generated by Django 5.0.2 on 2024-06-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula1site', '0019_user_is_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussiontopic',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.ImageField(upload_to='news_static/', verbose_name='Изображение'),
        ),
    ]
