# Generated by Django 5.0.2 on 2024-06-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula1site', '0020_remove_discussiontopic_created_by_alter_news_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='key',
            field=models.CharField(default=1, max_length=256, verbose_name='Ключевое слово'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='imageAvatar',
            field=models.ImageField(upload_to='ImageAvatar/', verbose_name='Изображение группы'),
        ),
        migrations.AlterField(
            model_name='group',
            name='imageHead',
            field=models.ImageField(upload_to='ImageHeader/', verbose_name='Шапка'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='StatementImage/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(upload_to='AvatarImage/', verbose_name='Аватар'),
        ),
    ]
